env:
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
service:
    - redis-server
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip3 install -r requirements.txt
script:
  - pip3 install -r redis_batch_test/requirements_for_test.txt
  - flake8
  - pytest  -x --cov-report term --cov=redis_batch  --durations=10 --show-capture=stdout -vv -rP --random-order redis_batch_test
  - vulture --min-confidence 100 redis_batch/
after_script:
  - coverage xml
